MATRIX_WIDTH = MATRIX_HEIGHT = 28
INPUTS = MATRIX_WIDTH * MATRIX_HEIGHT
OUTPUTS = 10

NETWORKS_DIRECTORY_PATH = "./data/networks"


NETWORK_TEMPLATES = [{"row sizes": [INPUTS, 30, 30, OUTPUTS]}]

NETWORK_MAIN_TEMPLATE_INDEX = 0
NETWORK_MAIN_TEMPLATE = NETWORK_TEMPLATES[NETWORK_MAIN_TEMPLATE_INDEX]
