MATRIX_WIDTH = MATRIX_HEIGHT = 28
INPUTS = MATRIX_WIDTH * MATRIX_HEIGHT
OUTPUTS = 10

ITERATIONS_FOR_EPOCH = 20
LEARNING_SPEED = 0.03

NETWORKS_DIRECTORY_PATH = "./data/networks/"


NETWORK_TEMPLATES = [[INPUTS, 30, 30, OUTPUTS], [INPUTS, 16, 16, OUTPUTS]]

NETWORK_MAIN_TEMPLATE_INDEX = 1
NETWORK_MAIN_TEMPLATE = NETWORK_TEMPLATES[NETWORK_MAIN_TEMPLATE_INDEX]
