MATRIX_WIDTH = MATRIX_HEIGHT = 28
INPUTS = MATRIX_WIDTH * MATRIX_HEIGHT
OUTPUTS = 10

ITERATIONS_FOR_EPOCH = 10
LEARNING_SPEED = 0.3

NETWORKS_DIRECTORY_PATH = "./data/networks/"


NETWORK_TEMPLATES = [[INPUTS, 30, 30, OUTPUTS], [INPUTS, 16, 16, OUTPUTS], [INPUTS, 30, OUTPUTS]]

NETWORK_MAIN_TEMPLATE_INDEX = 2
NETWORK_MAIN_TEMPLATE = NETWORK_TEMPLATES[NETWORK_MAIN_TEMPLATE_INDEX]
